### ISSUE TITLE
Are the example nodes wrong?

### ISSUE THREAD

**Issue by kriber82** [aaddrick/GPT-Actions#1]
As far as I understand the [OpenAPI Spec 3.1](https://swagger.io/specification/#media-type-object), example nodes (for instance in paths->/projects->get->responses->'200'->application/json->example) should contain the example object directly (in this case id: 220474322 and so on).

As far as I can tell, the subfields summary and value are intended for use in child-nodes of examples-node like [here](https://swagger.io/specification/#media-type-examples) in the OpenAPI Spec.

If you agree, I would be willing to prepare a PR changing all example: nodes to contain the examples directly.

**Comment by aaddrick** [comment]
100%. That change came out after I wrote this and I haven't had time to
revisit.

Feel free to write it up and I'll review and merge once it pops up.

EDIT: Thought this was in reference to the OpenAI description change originally. Ignore this comment.

Thanks much!

**Comment by aaddrick** [comment]
kriber82's fix merged. Thanks again!
